spring.application.name=booking-engine

spring.datasource.url=jdbc:postgresql://localhost:5432/booking
spring.datasource.username=borek497
spring.datasource.password=password8912
# sterownik bazy danych
spring.datasource.driver-class-name=org.postgresql.Driver
#tworzenie bazy danych
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GOOGLE_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash

#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=qwen3:4b-instruct
#spring.ai.ollama.chat.think=false
#spring.http.clients.connect-timeout=300s
#spring.http.clients.read-timeout=300s
#spring.ai.ollama.chat.keep-alive=30m
