spring.application.name=booking-engine

spring.datasource.url=jdbc:postgresql://localhost:5432/booking
spring.datasource.username=borek497
spring.datasource.password=password8912
# sterownik bazy danych
spring.datasource.driver-class-name=org.postgresql.Driver
#tworzenie bazy danych
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.show-sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
