### Pobranie wszystkich Properties
GET http://localhost:8080/properties

### Pobranie dostępnych pokoi po id
GET http://localhost:8080//properties/1/rooms/available

### Pobranie property po province
GET http://localhost:8080/properties?province=lubuskie

###
GET http://localhost:8080/properties?province=małopolskie&city=zakopane&propertyType=ROOMS